services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}  #optional
      - HASHED_PASSWORD=${HASHED_PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH} #optional
      - PROXY_DOMAIN=${PROXY_DOMAIN} #optional
      - DEFAULT_WORKSPACE=$DEFAULT_WORKSPACE #optional
    volumes:
      - ./data/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
