background_opacity 0.05
background_blur 30
background_image ~/.dotfiles/images/foxy.png
background_image_layout cscaled
background_tint 0.5
repaint_delay 5

window_alert_on_bell yes
enable_audio_bell no

tab_bar_style powerline
tab_powerline_style slanted
#tab_title_max_length 20
