# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a0226368-a345-4433-82ad-ef7ee7ed9c15";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a0226368-a345-4433-82ad-ef7ee7ed9c15".device =
    "/dev/disk/by-uuid/a0226368-a345-4433-82ad-ef7ee7ed9c15";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/186E-F0AC";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/tmp" = {
    device = "/dev/mapper/luks-84247b49-f908-42c4-81f3-69a6bc467295";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-84247b49-f908-42c4-81f3-69a6bc467295".device =
    "/dev/disk/by-uuid/84247b49-f908-42c4-81f3-69a6bc467295";

  swapDevices = [
    { device = "/dev/mapper/luks-d489ca0b-5100-4f98-aed8-4c862d04e403"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
