# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/
source= ~/.config/hypr/configs/autostart.conf
source= ~/.config/hypr/configs/env.conf
source= ~/.config/hypr/configs/input.conf
source= ~/.config/hypr/configs/style.conf
source= ~/.config/hypr/configs/windowrules.conf
source= ~/.config/hypr/monitors.conf
source= ~/.config/hypr/keybinds.conf

workspace = 5, layout:scrolling

debug {
  full_cm_proto=true
}

misc {
  vfr = true
}

###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
