# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e302746f-76e2-442a-8c66-7b53d5c11ab3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e302746f-76e2-442a-8c66-7b53d5c11ab3".device = "/dev/disk/by-uuid/e302746f-76e2-442a-8c66-7b53d5c11ab3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F7EE-2A9F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-25d105f0-c638-4d0f-8f3a-b90bf9e1f015"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  services.fstrim.enable = lib.mkDefault true; # ssd TRIM
}
