# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [
    "kvm-intel"
    "hid_apple.fnmode=2"
    "hid_apple.swap_fn_leftctrl=0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-e1e40fba-4bd2-454a-a265-e8e4efd09319";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e1e40fba-4bd2-454a-a265-e8e4efd09319".device =
    "/dev/disk/by-uuid/e1e40fba-4bd2-454a-a265-e8e4efd09319";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D91D-0CC9";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-b8abc530-b755-4eff-a41b-f58d9269ac56"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
